SELECT * FROM account
SELECT * FROM  client
SELECT * FROM disp
SELECT * FROM bank.order

-- *********** LOOKING FOR BAD ACCOUNTS ************

-- ACCOUNTS 
SELECT 
		LOAN.ACCOUNT_ID AS ACCOUNT_ID,  
        LOAN.LOAN_ID AS LOAN_ID,
        LOAN.DATE AS DATE_LOAN,
        LOAN.AMOUNT AS AMOUT_LOAN,
        LOAN.DURATION AS DURATION_LOAN,
        LOAN.PAYMENTS AS PAYMENTS_LOAN,
        LOAN.STATUS
/*
			(CASE WHEN LOAN.STATUS = 'A' THEN 'CONTRACT FINISHED - NO PROBLEMS'
                 WHEN LOAN.STATUS = 'B' THEN 'CONTRACT FINISHED - LOAN NOT PAYED'
                 WHEN LOAN.STATUS = 'C' THEN 'RUNNING CONTRACT - OK SO FAR'
                 ELSE 'RUNNING CONTRACT - CLIENT IN DEBT' END) as DESC_STATUS
*/
FROM	LOAN
WHERE 	LOAN.STATUS = 'B'
ORDER BY LOAN.ACCOUNT_ID




SELECT TYPE, COUNT(CARD_ID) FROM CARD
GROUP BY TYPE
-- CLASSIC: 659 / JUNIOR: 145 / GOLD: 88

-- ***** DISCOVER ACCOUNTS WITH GOLD CREDIT CARD
SELECT DISP.ACCOUNT_ID, CARD.CARD_ID, CARD.TYPE
FROM	DISP, CARD
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold'
SELECT * FROM DISP

-- ***** DEMOGRAPHIC DATA FOR ACCOUNTS WITH GOLD CREDIT CARD
SELECT 	
		DISP.ACCOUNT_ID AS ACCOUNT_ID, 
		CARD.CARD_ID AS CREDIT_CARD, 
        CARD.TYPE AS TYPE_CCARD, 
        DISP.CLIENT_ID AS CLIENT_ID,
        DISP.TYPE AS TYPE_DISPOSITION,
        CLIENT.DISTRICT_ID AS DISTRICT_ID, 
        DISTRICT.A3 AS REGION, 
        DISTRICT.A2 AS DISTRICT_NAME, 
        DISTRICT.A11 AS AVG_SALARY
FROM	DISP, CARD, CLIENT, DISTRICT
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND CLIENT.CLIENT_ID = DISP.CLIENT_ID AND DISTRICT.A1 = CLIENT.DISTRICT_ID
ORDER BY DISTRICT.A3, DISTRICT.A2
-- ***** DISTRICT / REGION WITH ACCOUNTS WITH GOLD CREDIT CARD
SELECT  DISTRICT.A2 AS DISTRICT_NAME, DISTRICT.A3 AS REGION, COUNT(DISTRICT.A1) AS COUNT_ACCOUNT, AVG(DISTRICT.A11) AS AVG_SALARY
FROM	DISP, CARD, CLIENT, DISTRICT
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND CLIENT.CLIENT_ID = DISP.CLIENT_ID AND DISTRICT.A1 = CLIENT.DISTRICT_ID
GROUP BY DISTRICT.A2, DISTRICT.A3
ORDER BY DISTRICT.A2, DISTRICT.A3

-- ***** REGION / DISTRICT WITH ACCOUNTS WITH GOLD CREDIT CARD
SELECT  DISTRICT.A3 AS REGION, DISTRICT.A2 AS DISTRICT_NAME,  COUNT(DISTRICT.A1) AS COUNT_ACCOUNT, AVG(DISTRICT.A11) AS AVG_SALARY
FROM	DISP, CARD, CLIENT, DISTRICT
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND CLIENT.CLIENT_ID = DISP.CLIENT_ID AND DISTRICT.A1 = CLIENT.DISTRICT_ID
GROUP BY DISTRICT.A3, DISTRICT.A2
ORDER BY DISTRICT.A3, DISTRICT.A2


-- **** ACCOUNTS WITH GOLD CREDIT CARD X LOAN -- THERE IS 1 LOAN / ACCOUNT
/* SELECT DISP.ACCOUNT_ID, CARD.CARD_ID, CARD.TYPE, LOAN.LOAN_ID, LOAN.STATUS,
			(CASE WHEN LOAN.STATUS = 'A' THEN 'CONTRACT FINISHED - NO PROBLEMS'
                 WHEN LOAN.STATUS = 'B' THEN 'CONTRACT FINISHED - LOAN NOT PAYED'
                 WHEN LOAN.STATUS = 'C' THEN 'RUNNING CONTRACT - OK SO FAR'
                 ELSE 'RUNNING CONTRACT - CLIENT IN DEBT' END) as DESC_STATUS */
SELECT 
		DISP.ACCOUNT_ID AS ACCOUNT_ID,  
        LOAN.LOAN_ID AS LOAN_ID,
        LOAN.DATE AS DATE_LOAN,
        LOAN.AMOUNT AS AMOUT_LOAN,
        LOAN.DURATION AS DURATION_LOAN,
        LOAN.PAYMENTS AS PAYMENTS_LOAN,
        LOAN.STATUS,
			(CASE WHEN LOAN.STATUS = 'A' THEN 'CONTRACT FINISHED - NO PROBLEMS'
                 WHEN LOAN.STATUS = 'B' THEN 'CONTRACT FINISHED - LOAN NOT PAYED'
                 WHEN LOAN.STATUS = 'C' THEN 'RUNNING CONTRACT - OK SO FAR'
                 ELSE 'RUNNING CONTRACT - CLIENT IN DEBT' END) as DESC_STATUS
FROM	DISP, CARD, LOAN
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND LOAN.ACCOUNT_ID = DISP.ACCOUNT_ID
ORDER BY DISP.ACCOUNT_ID

SELECT DISP.ACCOUNT_ID, COUNT(DISP.ACCOUNT_ID)
FROM	DISP, CARD, LOAN
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND LOAN.ACCOUNT_ID = DISP.ACCOUNT_ID
GROUP BY DISP.ACCOUNT_ID
ORDER BY DISP.ACCOUNT_ID

-- **** SUM ACCOUNTS WITH GOLD CREDIT CARD AND LOAN
SELECT LOAN.STATUS, 
			(CASE WHEN LOAN.STATUS = 'A' THEN 'CONTRACT FINISHED - NO PROBLEMS'
                 WHEN LOAN.STATUS = 'B' THEN 'CONTRACT FINISHED - LOAN NOT PAYED'
                 WHEN LOAN.STATUS = 'C' THEN 'RUNNING CONTRACT - OK SO FAR'
                 ELSE 'RUNNING CONTRACT - CLIENT IN DEBT' END) as DESC_STATUS,
		COUNT(LOAN.STATUS)
FROM	DISP, CARD, LOAN
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND LOAN.ACCOUNT_ID = DISP.ACCOUNT_ID
GROUP BY LOAN.STATUS
/*
A	CONTRACT FINISHED - NO PROBLEMS	8
C	RUNNING CONTRACT - OK SO FAR	7
D	RUNNING CONTRACT - CLIENT IN DEBT	1
*/

-- **** ACCOUNTS WITH GOLD CREDIT CARD X PERMANENT ORDER
SELECT * FROM BANK.ORDER

SELECT DISP.ACCOUNT_ID, ORDER.ORDER_ID, 
			(CASE WHEN ORDER.K_SYMBOL = 'POJISTNE' THEN 'INSURRANCE PAYMENT'
                 WHEN ORDER.K_SYMBOL = 'SIPO' THEN 'HOUSEHOLD PAYMENT'
                 WHEN ORDER.K_SYMBOL = 'LEASING' THEN 'LEASING'
                 ELSE 'LOAN PAYMENT' END) as TYPE_PAYMENT,
		ORDER.AMOUNT
FROM	DISP, CARD, BANK.ORDER
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND ORDER.ACCOUNT_ID = DISP.ACCOUNT_ID
ORDER BY DISP.ACCOUNT_ID

SELECT COUNT(DISTINCT DISP.ACCOUNT_ID)
FROM	DISP, CARD, BANK.ORDER
WHERE DISP.DISP_ID = CARD.DISP_ID AND CARD.TYPE = 'Gold' AND ORDER.ACCOUNT_ID = DISP.ACCOUNT_ID
ORDER BY DISP.ACCOUNT_ID
